---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: cnbattle/aigo
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  ref:
    - refs/heads/main
    - "refs/tags/**"