---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest
    pull: always
    image: plugins/manifest
    settings:
      ignore_missing: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest.tmpl

trigger:
  ref:
    - refs/heads/main
    - "refs/tags/**"