name: Publish of Runner
on:    
  release:
      types: [published]
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *' # at 02:00
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cnbattle/docker-go
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "runner"
        dockerfile: Dockerfile